---
name: Checks

on: [push]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted
    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Permission Change
        run: sudo chown -R $USER:$USER /home/ahmetsaidsaglam/github-actions/actions-runner/_work/recipe-app-api
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: pwd && ls && docker-compose up -d

      - name: Test
#        run: python3 app/manage.py test ./app/
        run: docker exec recipe-app python manage.py wait_for_db && docker exec recipe-app python manage.py test

      - name: Clean Containers
        if: always()
        run: docker-compose down --volumes