---
name: Checks

on: [push]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted
    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USER }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Checkout
#        uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d
      - name: Test
#        run: python3 app/manage.py test ./app/
        run: docker exec recipe-app python manage.py wait_for_db && python manage.py test
